server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hr_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: qaz84883233 # 修改这里
  thymeleaf:
    cache: false # 开发阶段关闭缓存

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印SQL
